version: "3.7"

services:
  domain-http:
    build:
      context: .
      dockerfile: https.Dockerfile
      target: apache-http
    volumes:
      - htdocs:/var/www/html
    ports:
      - 80:80
    profiles:
      - cert-issue
  
  cert-issue:
    build:
      context: .
      dockerfile: https.Dockerfile
      target: cert-issue
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    working_dir: /root
    volumes:
      - ./cert-issue.sh:/root/cert-issue.sh
      - htdocs:/root/htdocs
      - ./cert:/root/cert
      - ./.acme.sh:/root/.acme.sh
    depends_on: ["domain-http"]
    entrypoint: ./cert-issue.sh ${DOMAIN_NAME}
    profiles:
      - cert-issue

  cert-check:
    build:
      context: .
      dockerfile: https.Dockerfile
      target: apache-https
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./cert:/web/${DOMAIN_NAME}/cert
      - ./html:/web/${DOMAIN_NAME}/html
      # - ./${DOMAIN_NAME}-ssl.conf:/etc/apache2/sites-enabled/${DOMAIN_NAME}-ssl.conf
    profiles:
      - cert-check

volumes:
  htdocs: